source 'https://github.com/CocoaPods/Specs.git'

platform:ios, '8.0'
inhibit_all_warnings!
use_frameworks!

#target 'ShenmaEV' do
#    
#end

target 'fish-ios' do
    
    # Mappable
    pod 'ObjectMapper', '2.2.6'
    
    # Bugly
    pod 'Bugly', '~> 2.4.8'
    
    # SDWebImage
    pod 'SDWebImage', '3.8.2'
    
    # 网络图片处理库  Swift版SDWebImage
    pod 'Kingfisher', '3.13.1'
    
    # DDLog
    pod 'CocoaLumberjack','~>2.4.0'

  	# net request
	pod 'Alamofire', '~> 4.5.0'
   
	# layout
	pod 'SnapKit', '~> 3.2.0'

	# 下拉刷新
    pod 'MJRefresh', '~> 3.0.0'
    
    pod 'WebViewJavascriptBridge', '6.0.2'
  
end
